#   _ __   ___  ___  __ _ _ __   __ _
#  | '_ \ / _ \/ __|/ _` | '_ \ / _` |
#  | | | | (_) \__ \ (_| | | | | (_| |
#  |_| |_|\___/|___/\__,_|_| |_|\__,_|

include:
  - project: nosana-ci/tools/cicd/gitlab-ci
    file: docker-container.yml

variables:
  CONTAINER_PLATFORMS: linux/amd64
  DOCKERFILE_DIR: .
  RUN_AUTO_BUMP: ok
  AUTO_BUMP_REPO: nosana-ci/apps/platform/k8s
  AUTO_BUMP_FILE: helm-deployment-manager.tf
  AUTO_BUMP_SCG_PREFIX: image_tag [^}]*= { dev = \"

npm install:
  image: node:20.11.1
  stage: build
  script:
    - npm ci
  artifacts:
    untracked: true
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

npm format:
  image: node:20.11.1
  stage: test
  dependencies:
    - npm install
  script:
    - npm run format
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

npm test:
  image: node:20.11.1
  stage: test
  dependencies:
    - npm install
  script:
    - npm test
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

auto deploy prd:
  stage: .post
  extends: .auto-deploy
  variables:
    AUTO_BUMP_SCG_PREFIX: image_tag [^}]* prd = \"
  when: manual
